name: bootpay_bio
description:  A Bootpay bio plugin that provides payment api on Android, iOS.
version: 4.4.6

homepage: https://www.bootpay.co.kr
repository: https://github.com/bootpay/bootpay_flutter_bio.git

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  fluttertoast: ^8.0.9
  bootpay: 4.4.2
  carousel_slider: ^4.1.1
  intl: ^0.17.0
  otp: 3.1.1
  local_auth: 2.1.2
  local_auth_android: 1.0.15
  local_auth_ios: 1.0.10
  vibration: ^1.7.4-nullsafety.0
  shared_preferences: ^2.0.15
  get: ^4.6.5
  bootpay_webview_flutter: 3.2.44

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  http: ^0.13.3



# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
#  plugin:
#    platforms:
#      android:
#        package: kr.co.bootpay.bootpay_bio
#        pluginClass: BootpayBioPlugin
#      ios:
#        pluginClass: BootpayBioPlugin


  assets:
    - images/

  # To add assets to your plugin package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your plugin package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
